openapi: 3.0.1
info:
  title: Expenditure management
  version: 1.0.0
servers: 
  - url: http://localhost:8000/api/v1/admin
paths:
  /login:
    post:
      tags:
      - accounts
      summary: Đăng nhập vào hệ thống.
      requestBody:
          content:
            application/json:
              schema:
                required:
                  - email
                  - password
                properties:
                  email:
                    type: string
                  password:
                    type: string
                    format: password
          required: true
      responses:
        200:
          description: Request đã được tiếp nhận và xử lý thành công.
          content: 
            application/json:
              schema:
                properties:
                  token:
                    type: string
                    example: "abcxyzabcxyz123456789" 
        401:
          description: Unauthorized 
          content: 
            application/json:
              schema:
                  properties:
                    message:
                      type: string
                      example: "Tên đăng nhập và mật khẩu không hợp lệ"
        422:
          description: Unprocessable Entity - tên đăng nhập, password chưa được nhập, chưa đúng.
          content: 
              application/json:
                schema:
                  $ref: '#/components/schemas/ValidationError'
  /logout:
    put:
      tags:
      - accounts
      summary: Cập nhập mật khẩu theo id người dùng đang đăng nhập.
      requestBody:
        description: Đối tượng user cập nhập.
        content:
          application/json:
            schema:
              required:
                - current_password
                - password
                - confirm_password
              properties:
                current_password: 
                  type: string
                  format: password
                  description: Mật khẩu hiện tại.
                password: 
                  type: string
                  format: password
                  description: Mật khẩu mới.
                confirm_password: 
                  type: string
                  format: password
                  description: Xác nhận mật khẩu mới.
        required: true
      responses:
        201:
          description: Request đã được xử lý thành công.
        401:
          description: Unauthorized- người dùng chưa đăng nhập để thực hiện chức năng này.
        422:
          description: Unprocessable Entityy - current_password, password, confirm_password chưa được nhập, current_password, password, confirm_password chưa đúng.
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
  /group/{group_id}/members:
    get:
      tags:
      - members
      summary: Lấy tất cả thành viên của 1 nhóm
      parameters:
      - in: query
        name: group_id
        description: Nhóm
        required: true
        schema:
          type: string
      responses:
        200:
          description: Request đã được tiếp nhận và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Member'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
    post:
      tags:
        - members
      summary: Tạo member khi người dùng tạo nhu cầu hoặc mentor tạo nhóm
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Member'
        required: true
      responses:
        401: 
          description: Access token is missing or invalid
        405:
          description: Invalid input
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
    parameters:
      - in: path
        name: group_id
        description: Id nhóm
        required: true
        schema:
          type: string
  /group/members/{member_id}:
    put:
      tags:
        - members
      summary: Cập nhật thông tin thành viên (Duyệt vào nhóm)
      parameters:
      - name: member_id
        in: path
        description: member's id
        required: true
        schema:
          type: string
      requestBody:
        description: Updated member object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Member'
        required: true
      responses:
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
        404:
          description: member not found
        405:
          description: Invalid input
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
  /groups:
    get:
      tags:
      - groups
      summary: Lấy nhóm học đã được duyệt nhu cầu nhưng chưa được học kèm theo những điều kiện
      parameters:
      - name: isAccept
        in: query
        description: Nhóm đã được duyệt nhu cầu học chưa (không đi kèm)
        required: true
        schema:
          type: string
      - name: isStart
        in: query
        description: Nhóm đã được duyệt học chưa (không đi kèm)
        required: true
        schema:
          type: string
      - name: search
        in: query
        description: Tìm kiếm theo môn học (đi kèm với group_type)
        required: true
        schema:
          type: string
      - name: groupType
        in: query
        description: Loại nhóm là thiếu mentor, thiếu thành viên, hay tự học (đi kèm với search)
        required: true
        schema:
          type: string
      - name: account_id
        in: query
        description: Lấy toàn bộ ds group của một tài khoản (không đi kèm)
        required: true
        schema:
          type: string
      responses:
        200:
          description: Request đã được tiếp nhận và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
    post:
      tags:
        - groups
      summary: Tạo nhóm khi người dùng tạo nhu cầu hoặc mentor tạo nhóm
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      responses:
        401: 
          description: Access token is missing or invalid
        405:
          description: Invalid input
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
  /groups/{group_id}:
    get:
      tags:
      - groups
      summary: Lấy thông tin nhóm học (Khi nhấn vào nhóm ds nhóm chưa học, cần care vấn đề là id nhóm đã đc học, không nên cho xóa và sửa, tránh sửa thông tin lung tung)
      responses:
        200:
          description: Request đã được tiếp nhập và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
    put:
      tags:
        - groups
      summary: Cập nhật thông tin nhóm (Có thể cập nhật như là status khi mà admin duyệt, hoặc cho người tạo nhóm cập nhật thông tin nhóm khi nhóm chưa được duyệt. Nhưng khi người dùng cố tình push lên status nhóm thì server k update)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      responses:
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
        404:
          description: Group not found
        405:
          description: Invalid input
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
    delete:
      tags:
        - groups
      summary: Xóa nhóm chưa được accept đối với người tạo nhóm và xóa nhóm bất kỳ với admin
      parameters:
      - name: group_id
        in: path
        required: true
        schema:
          type: string
      responses:
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
        404:
          description: group not found
    parameters:
      - in: path
        name: group_id
        description: Id nhóm
        required: true
        schema:
          type: string
  /notifications:
    get:
      tags:
      - notifications
      summary: Lấy thông báo theo tìm kiếm
      parameters:
      - name: search
        in: query
        description: Tìm kiếm theo nội dung
        required: true
        schema:
          type: string
      responses:
        200:
          description: Request đã được tiếp nhập và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
    post:
      tags:
        - notifications
      summary: Tạo thông báo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
        required: true
      responses:
        401: 
          description: Access token is missing or invalid
        405:
          description: Invalid input
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
  /notifications/{id}:
    get:
      tags:
      - notifications
      summary: Lấy thông tin chi tiết thông báo (dành cho admin)
      responses:
        200:
          description: Request đã được tiếp nhập và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
    put:
      tags:
        - notifications
      summary: Cập nhật thông báo
      parameters:
      - name: id
        in: path
        description: notification's id
        required: true
        schema:
          type: string
      requestBody:
        description: Updated notification object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
        required: true
      responses:
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
        404:
          description: notification not found
        405:
          description: Invalid input
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
    delete:
      tags:
        - notifications
      summary: Xóa thông báo
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
        404:
          description: notification not found 
    parameters:
      - in: path
        name: id
        description: Id Thông báo
        required: true
        schema:
          type: string
  /questions:
    get:
      tags:
      - questions
      summary: Lấy danh sách câu hỏi
      responses:
        200:
          description: Request đã được tiếp nhập và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
  /answers:
    get:
      tags:
      - questions
      summary: Lấy danh sách câu trả lời
      responses:
        200:
          description: Request đã được tiếp nhập và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
  /users: 
    get:
      tags:
      - users
      summary: Lấy danh sách người dùng
      responses:
        200:
          description: Request đã được tiếp nhận và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserInfo'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
  /users/{user_id}:
    get:
      tags:
      - users
      summary: Lấy thông tin chi tiết người dùng
      responses:
        200:
          description: Request đã được tiếp nhập và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserInfo'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
    put:
      tags:
        - users
      summary: Cập nhật thông tin người dùng
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfoUpdate'
      responses:
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
        404:
          description: UserInfo not found
        405:
          description: Invalid input
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
components:
  schemas:
    UserInfo:
      type: object
      required:
        - phone_number
        - address
        - birthday
        - gender
        - faculty_id
        - full_name
        - is_active
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        phone_number:
          type: number
        address:
          type: string
        birthday:
          type: string
          format: date
        gender:
          type: boolean
        faculty_id:
          type: string
        full_name:
          type: string
        avatar_url:
          type: string
        is_active:
          type: boolean
        group:
          type: integer
    UserInfoUpdate:
      type: object
      required:
        - phone_number
        - address
        - birthday
        - gender
        - faculty_id
        - full_name
        - is_active
      properties:
        phone_number:
          type: number
        address:
          type: string
        birthday:
          type: string
          format: date
        gender:
          type: boolean
        faculty_id:
          type: number
        full_name:
          type: string
        avatar_url:
          type: string
        is_active:
          type: boolean
        rating:
          type: string
    Member:
      type: object
      required:
        - account_id
        - group_id
        - rating_mentor
        - is_creator
        - review
      properties:
        account_id:
          type: integer
        group_id:
          type: integer
        id_mentor:
          type: boolean
        is_creator:
          type: boolean
        cv_link:
          type: string
    Group:
      type: object
      required:
        - id
        - topic
        - information
        - student_amount
        - time_study
        - location_study
        - subject_id
        - status
      properties:
        amount:
          type: integer
        topic:
          type: string
        information:
          type: string
        time_stydy:
          type: string
          format: date-time
        location:
          type: string
        status:
          type: boolean
    Notification:
      type: object
      required:
        - id
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
    Question: 
      type: object
      required:
        - id
        - title
        - description
        - account_id
        - group_id
      properties:
        id:
          type: integer
        title: 
          type: string
        description: 
          type: string
        account_id: 
          type: integer
        group_id:
          type: integer
    Answer: 
      type: object
      required:
        - id
        - description
        - account_id
        - question_id
      properties:
        id:
          type: integer
        description: 
          type: string
        account_id: 
          type: integer
        question_id:
          type: integer
          
    ValidationError:
      type: object
      example: ['validation 1','validation 2']
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: [] 

