openapi: 3.0.1
info:
  title: Expenditure management
  version: 1.0.0
paths:
  /groups:
    get:
      tags:
      - groups
      summary: Lấy nhóm học đã được duyệt nhu cầu nhưng chưa được học kèm theo những điều kiện
      parameters:
      - name: isAccept
        in: path
        description: Nhóm đã được duyệt nhu cầu học chưa (không đi kèm)
        required: true
        schema:
          type: string
      - name: isStart
        in: path
        description: Nhóm đã được duyệt học chưa (không đi kèm)
        required: true
        schema:
          type: string
      - name: search
        in: path
        description: Tìm kiếm theo môn học (đi kèm với group_type)
        required: true
        schema:
          type: string
      - name: groupType
        in: path
        description: Loại nhóm là thiếu mentor, thiếu thành viên, hay tự học (đi kèm với search)
        required: true
        schema:
          type: string
      - name: account_id
        in: path
        description: Lấy toàn bộ ds group của một tài khoản (không đi kèm)
        required: true
        schema:
          type: string
      responses:
        200:
          description: Request đã được tiếp nhận và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
    post:
      tags:
        - groups
      summary: Tạo nhóm khi người dùng tạo nhu cầu hoặc mentor tạo nhóm
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      responses:
        401: 
          description: Access token is missing or invalid
        405:
          description: Invalid input
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
  /groups/{group_id}:
    get:
      tags:
      - groups
      summary: Lấy thông tin nhóm học (Khi nhấn vào nhóm ds nhóm chưa học, cần care vấn đề là id nhóm đã đc học, không nên cho xóa và sửa, tránh sửa thông tin lung tung)
      responses:
        200:
          description: Request đã được tiếp nhập và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
    put:
      tags:
        - groups
      summary: Cập nhật thông tin nhóm (Có thể cập nhật như là status khi mà admin duyệt, hoặc cho người tạo nhóm cập nhật thông tin nhóm khi nhóm chưa được duyệt. Nhưng khi người dùng cố tình push lên status nhóm thì server k update)
      parameters:
      - name: group_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      responses:
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
        404:
          description: Group not found
        405:
          description: Invalid input
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
    delete:
      tags:
        - groups
      summary: Xóa nhóm chưa được accept đối với người tạo nhóm và xóa nhóm bất kỳ với admin
      parameters:
      - name: group_id
        in: path
        required: true
        schema:
          type: string
      responses:
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
        404:
          description: group not found
components:
  schemas:
    Group:
      type: object
      required:
        - amount
        - topic
        - time_stydy
        - location
        - status
      properties:
        amount:
          type: integer
        topic:
          type: string
        information:
          type: string
        time_stydy:
          type: string
          format: date-time
        location:
          type: string
        status:
          type: boolean
    ValidationError:
      type: object
      additionalProperties:
        type: array
        example: ['validation 1','validation 2']
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
