openapi: 3.0.1
info:
  title: Expenditure management
  version: 1.0.0
paths:
  /group/members:
    get:
      tags:
      - members
      summary: Lấy tất cả thành viên của 1 nhóm
      parameters:
      - name: group_id
        in: path
        description: Nhóm
        required: true
        schema:
          type: string
      responses:
        200:
          description: Request đã được tiếp nhận và xử lý thành công.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/member'
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
    post:
      tags:
        - members
      summary: Tạo member khi người dùng tạo nhu cầu hoặc mentor tạo nhóm
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/member'
        required: true
      responses:
        401: 
          description: Access token is missing or invalid
        405:
          description: Invalid input
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
  /group/members/{member_id}:
    put:
      tags:
        - members
      summary: Cập nhật thông tin thành viên (Duyệt vào nhóm)
      parameters:
      - name: member_id
        in: path
        description: member's id
        required: true
        schema:
          type: string
      requestBody:
        description: Updated member object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/member'
        required: true
      responses:
        401: 
          description: Access token is missing or invalid
        403:
          description: Forbidden Error
        404:
          description: member not found
        405:
          description: Invalid input
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
components:
  schemas:
    member:
      type: object
      required:
        - account_id
        - group_id
        - id_mentor
        - is_creator
        - cv_link
      properties:
        account_id:
          type: integer
        group_id:
          type: integer
        id_mentor:
          type: boolean
        is_creator:
          type: boolean
        cv_link:
          type: string
    ValidationError:
      type: object
      additionalProperties:
        type: array
        example: ['validation 1','validation 2']
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

